//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPVOTING.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class votingEntitiesFinishing : DbContext
    {
        public votingEntitiesFinishing()
            : base("name=votingEntitiesFinishing")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_admin> tb_admin { get; set; }
        public DbSet<tb_team> tb_team { get; set; }
        public DbSet<tb_user> tb_user { get; set; }
    }
}
