//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPVOTING.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_admin
    {
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public string admin_username { get; set; }
        public string admin_password { get; set; }
        public string admin_level { get; set; }
    }
}
