//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPVOTING.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_team
    {
        public tb_team()
        {
            this.tb_user = new HashSet<tb_user>();
        }
    
        public int team_id { get; set; }
        public string team_name { get; set; }
        public string team_group { get; set; }
        public int jumlah_pemilih { get; set; }
        public int total_pemilih { get; set; }
    
        public virtual ICollection<tb_user> tb_user { get; set; }
    }
}
