//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPVOTING.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_user
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public string user_tempat_lahir { get; set; }
        public System.DateTime user_tanggal_lahir { get; set; }
        public Nullable<int> id_team { get; set; }
    
        public virtual tb_team tb_team { get; set; }
    }
}
